# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colaboratory.

"""

import random

#Add the code to create a list containing the three actions of the game.
listgame = ["rock","paper","scissors"]

#Add the code to set the scores of players to 0
player_score1 = 0
player_score2 = 0
#Add a round_counter that is 0 at the beginning
round_counter = 0

#Add the code to ask the user how many rounds they want to play
round = int(input("How many rounds will you play? "))

#Write a while loop and put the game inside
while True:

  #increase round_counter by 1 and print it
  round_counter +=1

  player1 = input("rock,paper,scissors?")
  #Add the code to select a random action for each player
  player2 = random.randint(0,3)
  player2 = random.choice(listgame)

  #Add the code to print the players choices
  print("Player2:",player2)

  #Add the tie condition
  if player1 == player2:
    player_score1 +=1
    player_score2 +=1
    print("Tie! oth players chose the same action")

  #Add the remaining condition
  elif player1 == "rock":
    if player2 == "paper":
      player_score2 +=1
      print("player2 won")
    else:
      player_score1 +=1
      print("You won")
  elif player1 == "paper":
    if player2 == "scissors":
      player_score2 +=1
      print("player2 won")
    else:
      player_score1 +=1
      print("You won")
  elif player1 == "rock":
    if player2 == "paper":
      player_score2 +=1
      print("player2 won")
  else:
    player_score1 +=1
    print("You won")

  #print the score
  print("Game scores:💯",player_score1,player_score2)

  #stop the while loop if the round_counter equals the number of total rounds
  if round_counter == round:
    break
#Print the outcome of the game by using conditional statements
if player_score1 > player_score2:
    print("You are the winner👋")
elif player_score1 < player_score2:
    print("player2 is the winner👋")
else:
    print("the game ended in a draw")
